version: '2'
services:
  mongodata:
    image: coralproject/mongodata
    restart: always
    environment:
      - "MONGO_DUMP=https://s3.amazonaws.com/coral-demo-dataset/dump.tar.gz"
      - "MONGO_USER=coraluser"
      - "MONGO_PASS=welcome"
      - "MONGO_DB=coral"
    volumes:
      - /mongodata:/data/db
    ports:
      - "27017:27017"


  pillarapp:
    image: coralproject/pillar:release
    restart: always
    environment:
        - "PILLAR_HOME=/opt/pillar"
        - "PILLAR_ADDRESS=:8080"
        - "MONGODB_URL=mongodb://coraluser:welcome@mongodata:27017/coral"
        - "PILLAR_CRON=false"
        - "PILLAR_CRON_SEARCH=@every 30m"
    ports:
     - "8080:8080"
    links:
      - mongodata


  cayapp:
    image: coralproject/cay:release
    restart: always
    environment:
       - "AUTH_TOKEN=NmQ3MmU2ZGQtOTNkMC00NDEzLTliNGMtODU0NmQ0ZDM1MTRlOlBDeVgvTFRHWjhOdGZWOGVReXZObkpydm4xc2loQk9uQW5TNFpGZGNFdnc9"
       - "PILLAR_URL=http://192.168.99.100:8080"
       - "ELKHORN_URL=http://192.168.99.100:4444"
       - "ENV=Demo"
       - "TRUST=false,"
       - "PROJECT=Coral Project"
    ports:
      - "80:80"
    links:
      - pillarapp
      - mongodata

  elkhorn:
    image: coralproject/elkhorn
    restart: always
    environment:
       - "PILLAR_URL=http://192.168.99.100:8080"
       - "AUTH_TOKEN=NmQ3MmU2ZGQtOTNkMC00NDEzLTliNGMtODU0NmQ0ZDM1MTRlOlBDeVgvTFRHWjhOdGZWOGVReXZObkpydm4xc2loQk9uQW5TNFpGZGNFdnc9"
       - "S3_BUCKET="
       - "AWS_REGION="
       - "AWS_ACCESS_KEY_ID="
       - "AWS_ACCESS_KEY="
    ports:
      - "4444:4444"
    links:
      - pillarapp
