version: '2'
services:
  mongodata:
    image: coralproject/mongodata
    restart: always
    environment:
      - "MONGO_DUMP=https://s3.amazonaws.com/coral-demo-dataset/coral-ask-bootsrap-dataset.tar.gz"
      - "MONGO_USER=${MONGO_USER}"
      - "MONGO_PASS=${MONGO_PASS}"
      - "MONGO_DB=${MONGO_DB}"
    volumes:
      - /mongodata:/data/db
    ports:
      - "27017:27017"


askapp:
    image: coralproject/askapp
    restart: always
    environment:
      - "XENIA_MONGO_HOST=mongodata:27017"
      - "XENIA_MONGO_AUTHDB=admin"
      - "XENIA_MONGO_DB=${MONGO_DB}"
      - "XENIA_MONGO_USER=${MONGO_USER}"
      - "XENIA_MONGO_PASS=${MONGO_PASS}"
      - "XENIA_LOGGING_LEVEL=1"
      - "XENIA_HOST=:4000"
    ports:
      - "4000:4000"
    links:
      - mongodata


  cayapp:
    image: coralproject/cay:release
    restart: always
    environment:
       - "AUTH_TOKEN=${AUTH_TOKEN}"
       - "ASK_URL=http://${FRONTEND_HOST}:4000"
       - "ELKHORN_URL=http://${FRONTEND_HOST}:4444"
       - "ENV=Demo"
       - "TRUST=false,"
       - "GAID=${GAID}"
       - "PROJECT=Coral Project"
    ports:
      - "80:80"
    links:
      - askapp
      - mongodata

  elkhorn:
    image: coralproject/elkhorn:release
    restart: always
    environment:
       - "ASK_URL=http://${FRONTEND_HOST}:4000"
       - "AUTH_TOKEN=${AUTH_TOKEN}"
       - "S3_BUCKET=${S3_BUCKET}"
       - "AWS_REGION=${AWS_REGION}"
       - "AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}"
       - "AWS_ACCESS_KEY=${AWS_ACCESS_KEY}"
    ports:
      - "4444:4444"
    links:
      - askapp
